# Generated by Django 4.1.7 on 2023-05-16 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_network', models.CharField(max_length=255, null=True)),
                ('market_value', models.CharField(default=0, max_length=1000, null=True)),
                ('crypto_code', models.CharField(max_length=255, null=True)),
                ('crypto_scan', models.ImageField(blank=True, null=True, upload_to='crypto')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_title', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Sapphire', 'Sapphire'), ('Diamond', 'Diamond')], max_length=255, null=True)),
                ('plan_image', models.ImageField(null=True, upload_to='plans')),
                ('prize', models.CharField(max_length=255, null=True)),
                ('duration', models.CharField(max_length=255, null=True)),
                ('interest', models.DecimalField(decimal_places=1, default=0, max_digits=9)),
                ('interest_duation', models.CharField(default='weekly', max_length=225, null=True)),
                ('referral', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('referral', models.CharField(blank=True, max_length=255, null=True)),
                ('user_wal_btc', models.CharField(blank=True, max_length=255, null=True)),
                ('user_wal_eth', models.CharField(blank=True, max_length=255, null=True)),
                ('user_wal_doge', models.CharField(blank=True, max_length=255, null=True)),
                ('user_wal_lite', models.CharField(blank=True, max_length=255, null=True)),
                ('user_balance', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('selected_network', models.CharField(blank=True, choices=[('1', 'Bitcoin'), ('2', 'Ethereum'), ('3', 'Dogecoin'), ('4', 'Litecoin')], max_length=255, null=True)),
                ('selected_wallet', models.CharField(blank=True, choices=[('1', 'Bitcoin'), ('2', 'Ethereum'), ('3', 'Dogecoin'), ('4', 'Litecoin')], max_length=255, null=True)),
                ('selected_code', models.CharField(blank=True, choices=[('1', 'Bitcoin'), ('2', 'Ethereum'), ('3', 'Dogecoin'), ('4', 'Litecoin')], max_length=255, null=True)),
                ('invested_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('crypto_value', models.DecimalField(decimal_places=7, default=0, max_digits=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_picture', models.ImageField(null=True, upload_to='team')),
                ('team_name', models.CharField(max_length=255, null=True)),
                ('team_comment', models.TextField(max_length=900, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(choices=[('Investment', 'Investment'), ('Withdrawal', 'Withdrawal')], default='Investment', max_length=255)),
                ('network', models.CharField(choices=[('BTC', 'Btc'), ('ETH', 'Eth'), ('DOGE', 'Doge'), ('LTC', 'Lite')], max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True, null=True)),
                ('trans_status', models.CharField(choices=[('Successful', 'Successful'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Successful', max_length=255)),
                ('trans_amount', models.CharField(max_length=255)),
                ('crypto_val', models.DecimalField(decimal_places=7, default=0, max_digits=15)),
                ('investor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gainapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='Admin', max_length=255)),
                ('chat_message', models.TextField(max_length=255)),
                ('chated_at', models.DateField(auto_now_add=True)),
                ('chated_time', models.TimeField(auto_now_add=True)),
                ('chat_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gainapp.profile')),
            ],
        ),
    ]
