# Generated by Django 4.1.7 on 2023-05-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_withdrawal',
            field=models.CharField(blank=True, default='0', max_length=255),
        ),
    ]
