# Generated by Django 4.1.7 on 2023-05-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_plan',
            field=models.CharField(blank=True, choices=[('Bronze Plan', 'Bronze'), ('Silver Plan', 'Silver'), ('Gold Plan', 'Gold'), ('Platinum Plan', 'Platinum'), ('Sapphire Plan', 'Sapphire'), ('Diamond Plan', 'Diamond')], max_length=255, null=True),
        ),
    ]
