# Generated by Django 4.1.7 on 2023-05-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0002_alter_profile_user_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_withdrawal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
