# Generated by Django 4.1.7 on 2023-05-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0002_profile_selected_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='crypto_value',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='crypto_val',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=18),
        ),
    ]
