# Generated by Django 4.1.7 on 2023-05-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0003_alter_profile_user_withdrawal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_withdrawal',
            new_name='withdrawal_request',
        ),
    ]
