# Generated by Django 4.1.7 on 2023-05-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0003_alter_profile_crypto_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='crypto_value',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='crypto_val',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=24),
        ),
    ]
