# Generated by Django 4.1.7 on 2023-05-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0004_rename_user_withdrawal_profile_withdrawal_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_balance',
            field=models.PositiveIntegerField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='withdrawal_request',
            field=models.PositiveIntegerField(blank=True, max_length=255, null=True),
        ),
    ]
