# Generated by Django 4.1.7 on 2023-05-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0005_profile_new_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='new_message',
        ),
        migrations.AddField(
            model_name='support',
            name='new_message',
            field=models.BooleanField(default=False),
        ),
    ]
