# Generated by Django 4.1.7 on 2023-05-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0005_alter_profile_user_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_balance',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='withdrawal_request',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
