# Generated by Django 4.1.7 on 2023-05-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0006_alter_profile_user_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='withdrawal_request',
            new_name='withdrawal_amount',
        ),
    ]
