# Generated by Django 4.1.7 on 2023-05-08 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0007_rename_withdrawal_request_profile_withdrawal_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Withdraw',
            new_name='Transaction',
        ),
    ]
