# Generated by Django 4.1.7 on 2023-05-08 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0008_rename_withdraw_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gainapp.profile'),
        ),
    ]
