# Generated by Django 4.1.7 on 2023-05-08 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0009_transaction_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gainapp.profile'),
        ),
    ]
