# Generated by Django 4.1.7 on 2023-05-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0010_crypto_investor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='crypto_network',
            field=models.CharField(choices=[('1', 'Bitcoin'), ('2', 'Ethereum'), ('3', 'Dodgecoin')], default='1', max_length=255),
        ),
    ]
