# Generated by Django 4.1.7 on 2023-05-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0011_alter_crypto_crypto_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='withdrawal_amount',
        ),
        migrations.AlterField(
            model_name='crypto',
            name='crypto_network',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum'), ('Dodgecoin', 'Dodgecoin')], default='Bitcoin', max_length=255),
        ),
    ]
