# Generated by Django 4.1.7 on 2023-05-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0012_remove_profile_withdrawal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='withdrawal_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
