# Generated by Django 4.1.7 on 2023-05-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0013_profile_withdrawal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='select_network',
            field=models.CharField(choices=[('1', 'Bitcoin'), ('2', 'Ethereum'), ('3', 'Dodgecoin')], default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_status',
            field=models.CharField(choices=[('Successful', 'Successful'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Successful', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(choices=[('Investment', 'Investment'), ('Withdrawal', 'Withdrawal')], default='Investment', max_length=255),
        ),
    ]
