# Generated by Django 4.1.7 on 2023-05-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0014_alter_profile_select_network_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='investor',
        ),
        migrations.AlterField(
            model_name='crypto',
            name='crypto_network',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
