# Generated by Django 4.1.7 on 2023-05-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0015_remove_crypto_investor_alter_crypto_crypto_network'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_wal',
            new_name='user_wal_btc',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_wal_dodge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_wal_eth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
