# Generated by Django 4.1.7 on 2023-05-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0016_rename_user_wal_profile_user_wal_btc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trans_network',
            field=models.CharField(choices=[('Btc', 'Btc'), ('Eth', 'Eth'), ('Dodge', 'Dodge')], default='Btc', max_length=255),
        ),
    ]
