# Generated by Django 4.1.7 on 2023-05-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0017_transaction_trans_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_network',
            field=models.CharField(choices=[('Btc', 'Btc'), ('Eth', 'Eth'), ('Dodge', 'Dodge')], max_length=255),
        ),
    ]
