# Generated by Django 4.1.7 on 2023-05-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0018_alter_transaction_trans_network'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='trans_network',
            new_name='network',
        ),
    ]
