# Generated by Django 4.1.7 on 2023-05-09 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0020_remove_profile_withdrawal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gainapp.profile'),
        ),
    ]
