# Generated by Django 4.1.7 on 2023-05-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0021_crypto_investor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='investor',
        ),
    ]
