# Generated by Django 4.1.7 on 2023-05-09 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0022_remove_crypto_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gainapp.profile'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='crypto_network',
            field=models.CharField(choices=[('Btc', 'Btc'), ('Eth', 'Eth'), ('Dodge', 'Dodge')], default='Btc', max_length=255),
        ),
    ]
