# Generated by Django 4.1.7 on 2023-05-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0023_crypto_investor_alter_crypto_crypto_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='investor',
        ),
        migrations.AlterField(
            model_name='crypto',
            name='crypto_network',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
