# Generated by Django 4.1.7 on 2023-05-09 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0024_remove_crypto_investor_alter_crypto_crypto_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='select_network',
        ),
    ]
