# Generated by Django 4.1.7 on 2023-05-09 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0026_profile_select_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='select_network',
        ),
    ]
