# Generated by Django 4.1.7 on 2023-05-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0031_alter_crypto_crypto_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='select_network',
            field=models.CharField(blank=True, choices=[('1', 'Bitcoin'), ('2', 'Ethereum'), ('3', 'Dodgecoin'), ('4', 'Litecoin')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='network',
            field=models.CharField(choices=[('Btc', 'Btc'), ('Eth', 'Eth'), ('Dodge', 'Dodge'), ('Lite', 'Lite')], max_length=255),
        ),
    ]
