# Generated by Django 4.1.7 on 2023-05-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0034_profile_selected_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='network_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
