# Generated by Django 4.1.7 on 2023-05-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0035_profile_network_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='crypto_scan',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
