# Generated by Django 4.1.7 on 2023-05-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0037_alter_crypto_crypto_scan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='crypto_scan',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='network_image',
        ),
    ]
