# Generated by Django 4.1.7 on 2023-05-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0038_remove_crypto_crypto_scan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='crypto_scan',
            field=models.ImageField(blank=True, null=True, upload_to='crypto'),
        ),
    ]
