# Generated by Django 4.1.7 on 2023-05-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0040_alter_crypto_crypto_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='network_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/crypto'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='crypto_scan',
            field=models.ImageField(blank=True, null=True, upload_to='crypto'),
        ),
    ]
