# Generated by Django 4.1.7 on 2023-05-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0041_profile_network_image_alter_crypto_crypto_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='network_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile/crypto'),
        ),
    ]
