# Generated by Django 4.1.7 on 2023-05-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0044_alter_profile_network_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_wal_lite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
