# Generated by Django 4.1.7 on 2023-05-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0045_profile_user_wal_lite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='select_network',
            field=models.CharField(blank=True, choices=[('1', 'Bitcoin'), ('2', 'Ethereum')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_code',
            field=models.CharField(blank=True, choices=[('1', 'Bitcoin'), ('2', 'Ethereum')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_wallet',
            field=models.CharField(blank=True, choices=[('1', 'Bitcoin'), ('2', 'Ethereum')], max_length=255, null=True),
        ),
    ]
