# Generated by Django 4.1.7 on 2023-05-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0049_alter_profile_select_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='select_network',
            field=models.CharField(blank=True, choices=[('1', 'Bitcoin'), ('2', 'Ethereum'), ('3', 'Dodgecoin'), ('4', 'Litecoin')], default='1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_code',
            field=models.CharField(blank=True, choices=[('1', 'Bitcoin'), ('2', 'Ethereum'), ('3', 'Dodgecoin'), ('4', 'Litecoin')], default='1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_wallet',
            field=models.CharField(blank=True, choices=[('1', 'Bitcoin'), ('2', 'Ethereum'), ('3', 'Dodgecoin'), ('4', 'Litecoin')], default='1', max_length=255, null=True),
        ),
    ]
