# Generated by Django 4.1.7 on 2023-05-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0052_alter_profile_select_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Boolean',
            field=models.BooleanField(default=False),
        ),
    ]
