# Generated by Django 4.1.7 on 2023-05-10 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0053_profile_boolean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Boolean',
        ),
    ]
