# Generated by Django 4.1.7 on 2023-05-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0054_remove_profile_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='network_image',
            field=models.FileField(blank=True, null=True, upload_to='profile/crypto'),
        ),
    ]
