# Generated by Django 4.1.7 on 2023-05-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0057_alter_crypto_crypto_scan_alter_profile_network_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='network_image',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
