# Generated by Django 4.1.7 on 2023-05-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0059_alter_profile_network_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='network_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/crypto'),
        ),
    ]
