# Generated by Django 4.1.7 on 2023-05-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0061_alter_crypto_crypto_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='crypto_scan',
            field=models.ImageField(blank=True, null=True, upload_to='crypto'),
        ),
    ]
