# Generated by Django 4.1.7 on 2023-05-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0062_alter_crypto_crypto_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='network_image',
            field=models.CharField(blank=True, choices=[('1', 'Bitcoin_scan'), ('2', 'Ethereum_scan'), ('3', 'Dodgecoin_scan'), ('4', 'Litecoin_scan')], max_length=255, null=True),
        ),
    ]
