# Generated by Django 4.1.7 on 2023-05-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0063_alter_profile_network_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='network_image',
            new_name='network_scan',
        ),
    ]
