# Generated by Django 4.1.7 on 2023-05-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0064_rename_network_image_profile_network_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='network_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/crypto'),
        ),
    ]
