# Generated by Django 4.1.7 on 2023-05-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0065_profile_network_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_picture', models.ImageField(null=True, upload_to='team')),
                ('team_name', models.CharField(max_length=255, null=True)),
                ('team_comment', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
