# Generated by Django 4.1.7 on 2023-05-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0066_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_comment',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
