# Generated by Django 4.1.7 on 2023-05-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0067_alter_team_team_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_comment',
            field=models.TextField(max_length=900, null=True),
        ),
    ]
