# Generated by Django 4.1.7 on 2023-05-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0069_alter_transaction_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='network',
            field=models.CharField(choices=[('BTC', 'Btc'), ('ETH', 'Eth'), ('DODGE', 'Dodge'), ('LTC', 'Lite')], max_length=255),
        ),
    ]
