# Generated by Django 4.1.7 on 2023-05-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0070_alter_transaction_network'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_wal_dodge',
            new_name='user_wal_doge',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='network_scan',
        ),
        migrations.AlterField(
            model_name='profile',
            name='select_network',
            field=models.CharField(blank=True, choices=[('1', 'Bitcoin'), ('2', 'Ethereum'), ('3', 'Dogecoin'), ('4', 'Litecoin')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_code',
            field=models.CharField(blank=True, choices=[('1', 'Bitcoin'), ('2', 'Ethereum'), ('3', 'Dogecoin'), ('4', 'Litecoin')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_wallet',
            field=models.CharField(blank=True, choices=[('1', 'Bitcoin'), ('2', 'Ethereum'), ('3', 'Dogecoin'), ('4', 'Litecoin')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='network',
            field=models.CharField(choices=[('BTC', 'Btc'), ('ETH', 'Eth'), ('DOGE', 'Doge'), ('LTC', 'Lite')], max_length=255),
        ),
    ]
