# Generated by Django 4.1.7 on 2023-05-12 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gainapp', '0071_rename_user_wal_dodge_profile_user_wal_doge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='network_image',
        ),
    ]
